### ISSUE TITLE
Application startup is slow

### ISSUE THREAD

**Issue by dilipkumar25** [dilipkumar25/smartecam-ai-samples#3]
The application takes around 5 minutes to load the model and then the camera preview to start. This gives the feeling that the application has stopped working until the model is fully loaded. This slow startup has to be fixed or at least the UI should be changed let the user know that loading is in progress.

**Comment by VikasSrinivasan** [comment]
The issue existed in the previous version of the application distribution. It has been solved in the recent version of the application distribution. 

Details : 

1. The camera will only start the stream after the model has been loaded. Till then, the application will display "Loading model"
